# Scripting option 1 (Main script)

trigger:
- main
- master
- devops

pool:
  vmImage: 'ubuntu-latest'                   #Use MS-hosted Ubuntu agent

steps:
- script: mvn validate
  displayName: 'Validate Maven Project'

- script: mvn compile
  displayName: 'Compile Maven Project'

- script: mvn test
  displayName: 'Unit Test Framework Maven Project'

- script: mvn package
  displayName: 'Generate Build Package/Artifact Maven Project'
  env:
    MAVEN_OPTS: -DskipTests=true     # skip tests while buildinh the artifact/package
    

#scripting options-2 form validation (no need to add validation 
#heare because Mavaen is advance tool if we justmention the step3 then it auto run the step1&2 post that run step3)
#trigger:
#- main
#- master
#- devops

#pool:
#  vmImage: 'ubuntu-latest'

#steps:
#- script: mvn compile
#  displayName: 'Compile Maven Project'

#scripting options-3 for test 

#trigger:
#- main
#- master
#- devops

#pool:
#  vmImage: 'ubuntu-latest's

#steps:
#- script: mvn test
#  displayName: 'Unit Test Framework Maven Project'


#scripting options-3 for test 

#trigger:
#- main
#- master
#- devops

#pool:
#  vmImage: 'ubuntu-latest's

#steps:
#- script: mvn test
#  displayName: 'Unit Test Framework Maven Project'

#- script: mvn package
#  displayName: 'Generate Build Package/Artifact Maven Project'